<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3aaadb9787f9f5107bce3305e4c3b064
{
    public static $files = array (
        'c952cfe799c6b7465da2cf780a8935417b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
        'c952cfe799c6b7465da2cf780a893541e69f7f6ee287b969198c3c9d6777bd38' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/bootstrap.php',
        'c952cfe799c6b7465da2cf780a89354125072dd6e2470089de65ae7bf11d3109' => __DIR__ . '/..' . '/symfony/polyfill-php72/bootstrap.php',
        'c952cfe799c6b7465da2cf780a893541c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'c952cfe799c6b7465da2cf780a893541a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'c952cfe799c6b7465da2cf780a893541f598d06aa772fa33d905e87be6398fb1' => __DIR__ . '/..' . '/symfony/polyfill-intl-idn/bootstrap.php',
        'c952cfe799c6b7465da2cf780a89354137a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'pxlrbt\\Cf7Cleverreach\\Vendor\\pxlrbt\\WordpressNotifier\\' => 54,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\Symfony\\Polyfill\\Php72\\' => 52,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 62,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\Symfony\\Polyfill\\Intl\\Idn\\' => 55,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\Psr\\Log\\' => 37,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\Psr\\Http\\Message\\' => 46,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\Monolog\\' => 37,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\GuzzleHttp\\Psr7\\' => 45,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\GuzzleHttp\\Promise\\' => 48,
            'pxlrbt\\Cf7Cleverreach\\Vendor\\GuzzleHttp\\' => 40,
            'pxlrbt\\Cf7Cleverreach\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'pxlrbt\\Cf7Cleverreach\\Vendor\\pxlrbt\\WordpressNotifier\\' => 
        array (
            0 => __DIR__ . '/..' . '/pxlrbt/wordpress-notifier/src',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php72',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\Symfony\\Polyfill\\Intl\\Idn\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-idn',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'pxlrbt\\Cf7Cleverreach\\Vendor\\GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'pxlrbt\\Cf7Cleverreach\\' => 
        array (
            0 => __DIR__ . '/../..' . '/classes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'pxlrbt\\Cf7Cleverreach\\Vendor\\Normalizer' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3aaadb9787f9f5107bce3305e4c3b064::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3aaadb9787f9f5107bce3305e4c3b064::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3aaadb9787f9f5107bce3305e4c3b064::$classMap;

        }, null, ClassLoader::class);
    }
}
